Repository runtipi/cli, pull requests merged in 2024-01, with the labels that each got.

#5 feat: add debug command
  Cargo.lock
  Cargo.toml
  rustfmt.toml
  src/args.rs
  src/commands/debug.rs
  src/commands/mod.rs
  src/commands/start.rs
  src/main.rs
Labels: size/L

#3 ci: build pipeline with cross-compile
  .github/workflows/build.yml
Labels: size/M

#7 feat: stop and restart commands
  src/args.rs
  src/assets/docker-compose.yml
  src/commands/mod.rs
  src/commands/start.rs
  src/commands/stop.rs
  src/main.rs
  src/utils/env.rs
Labels: size/L

#15 Revert all contributors
  .all-contributorsrc
  README.md
Labels: size/S
