Repository runtipi/cli, pull requests merged in 2025-05, with the labels that each got.

#102 fix: increase timeout for containers
  src/assets/docker-compose.yml
Labels: size/XS

#93 feat: init go cli
  go-cli/README.md
  go-cli/cmd/runtipi/main.go
  go-cli/go.mod
  go-cli/go.sum
  go-cli/internal/types/args.go
  go-cli/internal/types/version.go
Labels: size/L

#104 feat: start command in Go
  go-cli/cmd/runtipi/main.go
  go-cli/go.mod
  go-cli/go.sum
  go-cli/internal/commands/start.go
  go-cli/internal/components/console_box.go
  go-cli/internal/components/spinner.go
  go-cli/internal/utils/constants.go
  go-cli/internal/utils/env.go
  go-cli/internal/utils/schemas.go
  go-cli/internal/utils/seed.go
  go-cli/internal/utils/system.go
  go-cli/internal/utils/system_info.go
Labels: size/XL

#106 feat(go-cli): ensure file permissions & copy system files
  go-cli/assets/docker-compose.yml
  go-cli/internal/commands/start.go
  go-cli/internal/utils/system.go
Labels: size/L

#109 feat(go-cli): debug command
  go-cli/cmd/runtipi/main.go
  go-cli/go.mod
  go-cli/go.sum
  go-cli/internal/commands/debug.go
  go-cli/internal/utils/env.go
  go-cli/internal/utils/system_info.go
Labels: size/L

#110 feat(go-cli): reset password command
  go-cli/cmd/runtipi/main.go
  go-cli/internal/commands/reset_password.go
Labels: size/L

#112 feat(go-cli): list installed apps commands
  go-cli/cmd/runtipi/main.go
  go-cli/internal/commands/app.go
  go-cli/internal/commands/installed.go
  go-cli/internal/utils/api.go
Labels: size/L

#113 refactor(go-cli): use ldflags instead of embed version
  go-cli/cmd/runtipi/main.go
  go-cli/internal/assets/VERSION
  go-cli/internal/assets/assets.go
  go-cli/internal/commands/update.go
  go-cli/internal/config/config.go
  go-cli/internal/utils/system.go
Labels: size/M

#114 chore: move go cli to root and remove rust cli
  .github/workflows/ci.yml
  .github/workflows/nightly.yml
  Cargo.lock
  Cargo.toml
  cmd/runtipi/main.go
  go-cli/README.md
  go-cli/internal/assets/docker-compose.yml
  go.mod
  go.sum
  internal/assets/assets.go
  internal/assets/docker-compose.yml
  internal/commands/app.go
  internal/commands/debug.go
  internal/commands/installed.go
  internal/commands/reset_password.go
  internal/commands/start.go
  internal/commands/stop.go
  internal/commands/update.go
  internal/commands/version.go
  internal/components/console_box.go
  internal/components/spinner.go
  internal/config/config.go
  internal/types/args.go
  internal/types/version.go
  internal/utils/api.go
  internal/utils/archive.go
  internal/utils/constants.go
  internal/utils/env.go
  internal/utils/release.go
  internal/utils/schemas.go
  internal/utils/seed.go
  internal/utils/system.go
  internal/utils/system_info.go
  rustfmt.toml
  src/args.rs
  src/commands/app.rs
  src/commands/debug.rs
  src/commands/installed.rs
  src/commands/mod.rs
  src/commands/reset_password.rs
  src/commands/start.rs
  src/commands/stop.rs
  src/commands/update.rs
  src/commands/version.rs
  src/components/console_box.rs
  src/components/mod.rs
  src/components/spinner.rs
  src/main.rs
  src/utils/api.rs
  src/utils/constants.rs
  src/utils/env.rs
  src/utils/mod.rs
  src/utils/release.rs
  src/utils/schemas.rs
  src/utils/seed.rs
  src/utils/system.rs
  src/utils/tests/release.rs
Labels: size/XXL

#118 feat: add forward auth url to env generation
  internal/utils/constants.go
  internal/utils/env.go
  internal/utils/schemas.go
Labels: size/M
